### ISSUE TITLE
Traversing the links or How to validating the rights

### ISSUE THREAD

**Issue by KrishnaPG** [COALAIP/js-coalaip#6]
Came across this while looking for linked model for assets to be stored in BigChainDB. 

After converting data into this particular format, how to take advantage of its structure? For example, how to enforce if a person is the author or not (or has the required rights to it or not) ? or how to traverse the links and get the related data? Does the API cover such tasks?

**Comment by alexanderattar** [comment]
Hello @KrishnaPG,

This library is essentially just a JavaScript implementation of the COALA IP Spec. There is no logic within it to handle validating rights or anything like that, but rather it just just a format for structuring rights schemas. Also traversing linked data would be specific to the particular datastore that is used, which Coala IP is agnostic of. The BigchainDB team wrote a Python implementation of the spec that can upload to a BigchainDB instance, but the JavaScript implementation is designed to usable by any backend datastore such as IPFS, Swarm, Bigchain, or a traditional database. Please check out https://github.com/COALAIP/specs for more info.
